//
// Created by nikesh on 5/29/23.
//

#ifndef DELTARHO_CONTROLLER_I2C_H
#define DELTARHO_CONTROLLER_I2C_H

#include "pico/stdio.h"
#include "pico/stdlib.h"
// SDA and SCL pins on the Pico_W
#define SDA 20
#define SCL 21

// Datasheet for the PCA9685 at:
// https://www.nxp.com/docs/en/data-sheet/PCA9685.pdf
// Datasheet for the TB6612FNG at:
// https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf
//_________________________________________________________________________
// Set up the constants for the PCA9685

// User-defined via setting the jumpers on the board itself
#define PCA9685_ADDRESS 0

// Registers/etc:
#define MODE1 0x00;
#define MODE2 0x01;

#define PRESCALE 0xFE;

// Used for setting the PWM signal generated by the onboard clock
#define LED0_ON_L 0x06;
#define LED0_ON_H 0x07;
#define LED0_OFF_L 0x08;
#define LED0_OFF_H 0x09;

// Bits:
#define RESTART 0x80;
#define SLEEP 0x10;
#define ALLCALL 0x01;
#define INVRT 0x10;
#define OUTDRV 0x04;

//_________________________________________________________________________
// Set up the constants for the TB6612FNG

//_________________________________________________________________________

void __init__i2c__();

void __reset__();

void setMotorPWM();

#endif // DELTARHO_CONTROLLER_I2C_H
