//
// Created by nikesh on 7/3/23.
//

#ifndef DELTARHO_CONTROLLER_LWIPOPTS_H
#define DELTARHO_CONTROLLER_LWIPOPTS_H

#define LWIP_TIMEVAL_PRIVATE 0
#define LWIP_IPV4 1

#endif // DELTARHO_CONTROLLER_LWIPOPTS_H
