//
// Created by nikesh on 7/3/23.
//

#ifndef DELTARHO_CONTROLLER_LWIPOPTS_H
#define DELTARHO_CONTROLLER_LWIPOPTS_H

#define MEMP_NUM_SYS_TIMEOUT (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 1)
#define LWIP_TCP 1
#define LWIP_TIMEVAL_PRIVATE 0
#define LWIP_IPV4 1

#endif // DELTARHO_CONTROLLER_LWIPOPTS_H
