//
// Created by nikesh on 7/8/23.
//

#ifndef DELTARHO_CONTROLLER_ROBOT_CONFIG_H
#define DELTARHO_CONTROLLER_ROBOT_CONFIG_H

#define ROBOT_NUMBER 1
#define SOCKET_CONNECTION
// #define MQTT_CONNECTION

#endif // DELTARHO_CONTROLLER_ROBOT_CONFIG_H
